---
- name: Download CloudWatch Agent
  ansible.builtin.apt:
    deb: https://amazoncloudwatch-agent-eu-central-1.s3.eu-central-1.amazonaws.com/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb

- name: Copy CloudWatch configuration
  ansible.builtin.template:
    src: amazon-cloudwatch-agent.json.j2
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    owner: root
    group: root
    mode: "0644"

- name: Start CloudWatch Agent
  ansible.builtin.command: >
    /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
    -a fetch-config
    -m ec2
    -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    -s